/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Launcher;

import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;

/**
 *
 * @author Usuario
 */
public class VistaHome extends javax.swing.JPanel {

    public JLabel[] simuladores;
    
    public Fondobase padre;
    
    public VistaHome() {
                  
        initComponents();
        
        simuladores = new JLabel[]{simulador0,simulador1, simulador2,simulador3, simulador4, simulador5};
        
        for(int x = 0; x < simuladores.length; x++){
            Utility.SetImageLabelForced(simuladores[x], "src/Pics/Grado"+x+".png", new Dimension(381, 291));
            
            addHoverEffect(simuladores[x], x);
        }     
    }       

  // Método para añadir el efecto de mover a un JLabel
    private void addHoverEffect(JLabel label, int indice) {
        
        // Agregar un MouseListener al JLabel
        label.addMouseListener(new MouseAdapter() {
            @Override
          
            public void mouseEntered(MouseEvent e) {
                Utility.SetImageLabelForced(label, "src/Pics/Grado"+indice+".png", new Dimension(401,311));
            }
            
            @Override
            public void mouseExited(MouseEvent e) {
               Utility.SetImageLabelForced(label, "src/Pics/Grado"+indice+".png", new Dimension(381, 291));
            }
            
            @Override
            public void mouseClicked(MouseEvent e) {
               padre.ColocarPanelCarrusel(indice);
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        simulador0 = new javax.swing.JLabel();
        simulador1 = new javax.swing.JLabel();
        simulador2 = new javax.swing.JLabel();
        simulador3 = new javax.swing.JLabel();
        simulador4 = new javax.swing.JLabel();
        simulador5 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new java.awt.GridLayout(2, 3));

        simulador0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        simulador0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Grado5.png"))); // NOI18N
        add(simulador0);

        simulador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        simulador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Grado2.png"))); // NOI18N
        add(simulador1);

        simulador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        simulador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Grado1.png"))); // NOI18N
        add(simulador2);

        simulador3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        simulador3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Grado0.png"))); // NOI18N
        add(simulador3);

        simulador4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        simulador4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Grado3.png"))); // NOI18N
        add(simulador4);

        simulador5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        simulador5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Grado4.png"))); // NOI18N
        add(simulador5);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel simulador0;
    private javax.swing.JLabel simulador1;
    private javax.swing.JLabel simulador2;
    private javax.swing.JLabel simulador3;
    private javax.swing.JLabel simulador4;
    private javax.swing.JLabel simulador5;
    // End of variables declaration//GEN-END:variables
}
