/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Launcher;

import java.awt.Dimension;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Usuario
 */
public class VistaCarrusel extends javax.swing.JPanel {

    public int index = 0;
    
    public int numeroSimulador;
    
     String nombreImagen;
    
    public VistaCarrusel(int simulador) {
        initComponents();
        
        numeroSimulador = simulador;

        
      
        
        Utility.SetImageLabelForced(ImagenPrincipal, "src/Pics/"+  LeerNombre() + index + ".png", new Dimension(891, 525));
        
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImagenPrincipal = new javax.swing.JLabel();
        FlechaIzquierda = new javax.swing.JLabel();
        FlechaDerecha = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImagenPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImagenPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Embarque0.png"))); // NOI18N
        add(ImagenPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 950, 560));

        FlechaIzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Flecha izquierda.png"))); // NOI18N
        FlechaIzquierda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FlechaIzquierdaMouseClicked(evt);
            }
        });
        add(FlechaIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 40, 80));

        FlechaDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Flecha derecha.png"))); // NOI18N
        FlechaDerecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FlechaDerechaMouseClicked(evt);
            }
        });
        add(FlechaDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 350, 40, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void FlechaIzquierdaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlechaIzquierdaMouseClicked
        index--;
        
        if(index < 0) index = 4;
        
        
        
        Utility.SetImageLabelForced(ImagenPrincipal, "src/Pics/"+  LeerNombre()+ index + ".png");
    }//GEN-LAST:event_FlechaIzquierdaMouseClicked

    private void FlechaDerechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlechaDerechaMouseClicked
        index++;
        
        if(index >4) index = 0;
        
        
        
        Utility.SetImageLabelForced(ImagenPrincipal, "src/Pics/"+  LeerNombre()+ index + ".png");
    }//GEN-LAST:event_FlechaDerechaMouseClicked

    
    public String LeerNombre(){
        try {
            nombreImagen = Utility.NombreImagenCarrusel(numeroSimulador);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(VistaCarrusel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return nombreImagen;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FlechaDerecha;
    private javax.swing.JLabel FlechaIzquierda;
    private javax.swing.JLabel ImagenPrincipal;
    // End of variables declaration//GEN-END:variables
}
